<?php require("template/header.phtml") ?>

<div class="row">
    <h3 class="mt-3">What is PetWatch about?</h3>
    <p>PetWatch is an online platform that helps reunite missing pets with their owners.
        It provides a secure space where pet owners can create and manage listings for their pets, and community members
        can browse and search reports or share sightings of animals they’ve found.</p>
    <h3 class="mt-3">Navigation</h3>
    <p>Use the header above to navigate through all the website pages.</p>
    <h3 class="mt-3">Login</h3>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        Warning: You must be logged-in to use certain features of PetWatch such as to manage your pets or add sightings
        about missing pets.
    </div>
    <p>To log in with your user account, simply use the Login button on the top right and insert your credentials!</p>
    <h2 class="mt-3">Good luck finding your pet!</h2>
</div>

<?php require('template/footer.phtml') ?>
